### ISSUE TITLE
Lack of peasants after some time

### ISSUE THREAD

**Issue by kufdaw** [CrusaderPilaw/Legends-Of-The-Orient#1]
When I am doing 4 vs 4 game then after some time almost all AI's or most of them are having lack of peasants issue. When I am making smaller games, like 2vs2 or sth like that this is not very likely to occur but also happening sometimes. I tried different "Let the AI build houses smarter", like turning it off, on, default values, minimum, maximum etc, but it always behaves the same. 
So I have all files copied and after that I click uninstall, then change values and then click install. Maybe I am reinstalling it wrong way?

**Comment by CrusaderPilaw** [comment]
I would guess that you started Crusader, and not Extreme?
In Crusader the troop limit is 2500, once this cap is reached the AI gets bugged. In Extreme it's much higher, 10.000. :)
Let me know if this fixes it!

**Comment by kufdaw** [comment]
OMG! That was the problem, now it is working. Just imagine how much time I spent on looking for an issue! Thank you!
